name: contact_app
description: Assessment for RF Infinite.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  flutter_riverpod: 2.1.1
  riverpod_annotation: ^1.0.6
  freezed_annotation: 2.1.0
  go_router: 6.0.1
  path_provider: 2.0.11
  retrofit: ^3.3.1
  sembast: ^3.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.2.1
  retrofit_generator: ^4.2.0
  riverpod_generator: ^1.0.6
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true