name: contact_app
description: Assessment for RF Infinite.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: 2.1.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  freezed_annotation: 2.1.0
  go_router: 6.0.1
  path_provider: 2.0.11
  retrofit: ^3.3.1
  riverpod_annotation: ^1.0.6
  sembast: ^3.3.1+1

dev_dependencies:
  build_runner: 2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  assets:
    - assets/images/
    - assets/svg/
